image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva
    - GitHub.github-vscode-theme
    - mhutchie.git-graph
    - MS-vsliveshare.vsliveshare
    - mtxr.sqltools
    - mtxr.sqltools-driver-sqlite
